### ISSUE TITLE
Cannot access drive files

### ISSUE THREAD

**Issue by KShivendu** [viveklinkin/SharinGAN#1]
Hii there,
I am getting the following error:
`ApiRequestError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/1FxxjLtm-C_2c5H8ZNQLg8vV92E4-VKPn?alt=json returned "File not found: 1FxxjLtm-C_2c5H8ZNQLg8vV92E4-VKPn">`

[The corresponding url](https://www.googleapis.com/drive/v2/files/1FxxjLtm-C_2c5H8ZNQLg8vV92E4-VKPn?alt=json) says - `Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup`. 
Please have a look at the shared drive files.

Thanks

**Comment by viveklinkin** [comment]
Hi Kumar, 

Thank you for your interest in our project. Looks like the collab link has expired. The backup file is https://github.com/viveklinkin/SharinGAN/blob/master/SharinGAN.ipynb. You can copy paste the code in a new collab project and work from there.
Find the original repo (which our project was based on) here: https://github.com/KupynOrest/DeblurGAN

Best regards,
Vivek
